version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-packaging-dependencies-{{ checksum "client/package-lock.json" }}
      - run:
          name: Install dependencies
          working_directory: client
          command: npm ci
      - save_cache:
          paths:
            - client/node_modules
          key: v2-packaging-dependencies-{{ checksum "client/package-lock.json" }}

  unit-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-packaging-dependencies-{{ checksum "client/package-lock.json" }}
      - run:
          name: Run unit tests
          working_directory: client
          command: npm run test:ci
      - store_test_results:
          path: client/reports

  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-packaging-dependencies-{{ checksum "client/package-lock.json" }}
      - run:
          name: Run linter
          working_directory: client
          command: npm run lint

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-packaging-dependencies-{{ checksum "client/package-lock.json" }}
      - run:
          name: Create .env.local file
          working_directory: client
          command: |
            echo -e "VUE_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN\nVUE_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID\nVUE_APP_HASURA_HTTP=$HASURA_ENDPOINT/v1/graphql\nVUE_APP_HASURA_WSS=$HASURA_WSS\n" >> .env.local
      - run:
          name: Build frontend
          working_directory: client
          command: npm run build
      - persist_to_workspace:
          root: client/dist
          paths:
            - ./*

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: client/dist
      - run:
          name: Deploy frontend
          working_directory: client/dist
          command: |
            git config --global user.email "vincent.landais@zenika.com"
            git config --global user.name "VincentLANDAIS"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link $CLEVER_FRONT_APP_ID
            clever deploy --force

  deploy-remote-schema:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy remote schema
          working_directory: server/remote-schema
          command: |
            git config --global user.email "vincent.landais@zenika.com"
            git config --global user.name "VincentLANDAIS"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link $CLEVER_REMOTE_SCHEMA_APP_ID
            clever deploy --force

  deploy-hasura:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy Hasura
          working_directory: server
          command: |
            git config --global user.email "vincent.landais@zenika.com"
            git config --global user.name "VincentLANDAIS"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link $CLEVER_HASURA_APP_ID
            clever deploy --force

  run-hasura-migrations:
    docker:
      - image: hasura/graphql-engine:v2.3.1.cli-migrations-v3
    steps:
      - checkout
      - run:
          name: Apply migrations
          working_directory: server
          command: hasura-cli migrate apply --all-databases --admin-secret $HASURA_ADMIN_SECRET --endpoint $HASURA_ENDPOINT
      - run:
          name: Apply metadata
          working_directory: server
          command: hasura-cli metadata apply --admin-secret $HASURA_ADMIN_SECRET --endpoint $HASURA_ENDPOINT

  deploy-auth0:
    docker:
      - image: circleci/node:lts
    parameters:
      config-file:
        type: string
      deploy-client-id:
        type: string
      deploy-secret:
        type: string
    steps:
      - checkout
      - run:
          name: Create .env.local file
          working_directory: auth0
          command: echo -e "HASURA_ADMIN_SECRET=$HASURA_ADMIN_SECRET\nADMIN_USER_ID=$ADMIN_USER_ID\nHASURA_SYNC_USER_RULE_URL=$HASURA_ENDPOINT/v1/graphql\nAUTH0_CLIENT_ID=<< parameters.deploy-client-id >>\n" >> .env.local
      - run:
          name: Install auth0 CLI
          working_directory: auth0
          command: sudo npm i -g auth0-deploy-cli
      - run:
          command: |
            echo << parameters.config-file >>
            echo << parameters.deploy-secret >>
            echo << parameters.deploy-client-id >>
      - run:
          name: Deploy Auth0 tenant
          working_directory: auth0
          command: export $(cat .env.local | xargs) && a0deploy import --config_file << parameters.config-file >> --input_file tenant.yaml -x << parameters.deploy-secret >>

workflows:
  main:
    jobs:
      # - install-dependencies
      # - unit-test:
      #     requires:
      #       - install-dependencies
      # - lint:
      #     requires:
      #       - install-dependencies
      # - build:
      #     requires:
      #       - unit-test
      #       - lint
      - deploy-auth0:
          name: deploy-auth0-staging
          config-file: staging-config.json
          deploy-client-id: $AUTH0_DEPLOY_CLIENT_ID_STAGING
          deploy-secret: $AUTH0_DEPLOY_SECRET_STAGING
      - deploy-auth0:
          name: deploy-auth0-prod
          filters: &prod-filters
            branches:
              only: main
          config-file: prod-config.json
          deploy-client-id: $AUTH0_DEPLOY_CLIENT_ID
          deploy-secret: $AUTH0_DEPLOY_SECRET
      # - deploy-remote-schema:
      #     requires:
      #       - deploy-auth0
      #     filters: *prod-filters
      # - deploy-hasura:
      #     requires:
      #       - deploy-remote-schema
      #     filters: *prod-filters
      # - run-hasura-migrations:
      #     requires:
      #       - deploy-hasura
      #     filters: *prod-filters
      # - deploy:
      #     requires:
      #       - build
      #       - run-hasura-migrations
      #     filters: *prod-filters

