# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:lts
    working_directory: client
    steps:
      - checkout: ..
      # - restore_cache:
      #     keys:
      #       - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
      #       - v4-packaging-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v4-packaging-dependencies-{{ checksum "package-lock.json" }}

  unit-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "client/package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          command: ls -l
      - run:
          working_directory: client
          command: ls -l
      - run:
          name: Run unit tests
          working_directory: client
          command: npm run test:unit

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "client/package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: Build frontend
          working_directory: client
          command: npm run build


  deploy-hasura:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/node:lts
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Deploy Hasura
          working_directory: server
          command: |
            git config --global user.email "vincent.landais@zenika.com"
            git config --global user.name "VincentLANDAIS"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link $CLEVER_APP_ID
            clever deploy --force

  run-hasura-migrations:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: install hasura cli
          command: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      - run:
          name: Apply migrations
          working_directory: server
          command: hasura migrate apply --all-databases --admin-secret $HASURA_ADMIN_SECRET --endpoint $HASURA_ENDPOINT
      - run:
          name: Apply metadata
          working_directory: server
          command: hasura metadata apply --admin-secret $HASURA_ADMIN_SECRET --endpoint $HASURA_ENDPOINT

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-prod:
    jobs:
      - install-dependencies
      - unit-test:
          requires:
            - install-dependencies
      - build:
          requires:
            - unit-test
      - deploy-hasura:
          requires:
            - build
          # filters: &deploy-filters
          #   branches:
          #     only: main
      - run-hasura-migrations:
          requires:
            - deploy-hasura
          # filters: *deploy-filters
